---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-azurefile-demo
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Gi
  storageClassName: azurefile-csi-demo

---
kind: Pod
apiVersion: v1
metadata:
  name: nginx-azurefile
spec:
  nodeSelector:
    kubernetes.io/os: linux
  containers:
    - image: mcr.microsoft.com/oss/nginx/nginx:1.17.3-alpine
      name: nginx-azuredisk
      command:
        - "/bin/sh"
        - "-c"
        - while true; do echo $(date) >> /mnt/azuredisk/outfile; sleep 1; done
      volumeMounts:
        - name: azurefile01
          mountPath: "/mnt/azuredisk"
  volumes:
    - name: azurefile01
      persistentVolumeClaim:
        claimName: pvc-azurefile-demo